#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/opt/openssl/bin
  /usr/local/{bin,sbin}
  /usr/local/opt/llvm/bin  
  /usr/local/bin/npm/bin
  /usr/local/opt/libxml2/bin
  /Library/TeX/texbin
  /usr/sbin
  /sbin
  ~/bin
  /usr/local/opt/elasticsearch@5.6/bin
  /usr/local/opt/openldap/sbin
  /Users/nakagawasohei/Library/Python/3.7/bin
  ~/.nodebrew/current/bin
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
#if (( $#commands[(i)lesspipe(|.sh)] )); then
#  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
#  echo 'export PATH=$PATH:/usr/local/Cellar/llvm/HEAD-1d6becb/bin' >> .zshrc
#fi
